#!/usr/bin/env bash

usage() {
    echo "Usage: ${0/*\//} [OPTIONS]"
    echo
    echo "Install or uninstall certify script"
    echo
    echo "Options:"
    echo "    -h, --help         Display this help message"
    echo "    -u, --uninstall    Uninstall"
    echo
    exit $1
}

declare -a args
action="install"

while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-h"|"--help") usage 0 ;;
        "-u"|"--uninstall") action="uninstall" ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ -z ${args[@]} ]] || set -- "${args[@]}"

[[ $# -eq 0 ]] || usage 1

case "$action" in
    "install") mkdir -p $HOME/bin; install -m 700 certify $HOME/bin ;;
    "uninstall") rm -f $HOME/bin/certify ;;
    *) usage 2 ;;
esac
